### ISSUE TITLE
What about crossplatform?..

### ISSUE THREAD

**Issue by kai66673** [ltcmelo/uaiso#5]
My crossplatform compile expirience:

Windows:
1. Only msvc 2015
2. GenFlexBison.py:
  a) call(["mv",...) -> os.rename(...)
  b) call(["flex", "%s/%s.l" % (lang, lang)]) -> call(["win_flex", "--wincompat", "%s/%s.l" % (lang, lang)])
      call(["bison", "-d", "-v", "%s/%s.y" % (lang, lang)]) -> call(["win_bison", "-d", "-v", "%s/%s.y" % (lang, lang)])
     It's possible detect OS by python and call appropriate utils.
3. dllexport hell for STL class members. My suggestion is switch from sdt::string to Literal (implemented into qtcreator sources)

Linux (Ubuntu 14.04, gcc 4.8.2)
1. Not supported auto for function (lambda) arguments.
I fix this in CompletionProposer.cpp.

As a result, I was able to build library for Windows and Ubuntu 14.04.

Are you interested in the adaptation library sources for use on the three major platforms (MAC, Linux, Windows)?

**Comment by ltcmelo** [comment]
Sorry for the late reply, Kai. Thanks for your efforts and the wrap-up, I'd be definitely interested on your adaptations if you'd like to contribute them. (Indeed generic lambdas are supported only on gcc 4.9.)

I don't like the idea of replacing std::string for something like QtCreator's Literal though. Eventually I'll have other STL classes in the DLL interface and this strategy won't scale. But notice this issue is MSVC specific, since it imposes "stronger" requirements for classes on DLL boundaries. The following might be a way out: https://support.microsoft.com/en-us/kb/168958

Apart from compilation, you've probably noticed that there's code that won't work on Windows. In particular, the FileInfo class, which currently relies UNIX-like paths. I haven't looked into this yet both due to time (un)availability and because I only have an OSX in hands.

**Comment by kai66673** [comment]
Ok. Pull request is queued...

**Comment by ltcmelo** [comment]
Thanks, just merged it.
